pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "flask-web-app:${env.BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                git(branch: 'main',
                    url: 'https://github.com/Lavanya-20-git/Cloud.git',
                    credentialsId: 'ubuntuaccess')
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build(DOCKER_IMAGE)
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    sh "docker stop flask-app || true"
                    sh "docker rm flask-app || true"
                    sh "docker run -d -p 80:5000 --name flask-app ${DOCKER_IMAGE}"
                }
            }
        }
    }
}
